version: '3.8'
services:

  #PHP Service
  app:
    build:
      dockerfile: Dockerfile
      context: ./ophim-cms
    image: laravel-image
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./ophim-cms/:/var/www/html
    networks:
      - ophim_network

  # Golang Service
  go_api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: debug
      PORT: :8080
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: movies
      DB_USERNAME: root
      DB_PASSWORD: rootpasswordmysql
    networks:
      - ophim_network
    restart: unless-stopped
  
  #Nginx Service
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./ophim-cms/:/var/www/html
      - ./ophim-cms/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ophim_network

  #DB Service
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
      MYSQL_AUTH_PLUGIN: mysql_native_password
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      # Opens port 8080 on the container
      - "3306"
    networks:
      - ophim_network

networks:
  ophim_network:
    driver: bridge

volumes:
  mysql-database:
    driver: local
